#!/usr/bin/env python

import numpy as np

print("/* This file was auto-generated by gen_map.py */")
print("")
print("#include <project.h>")
print("")
print("#include \"pixel_map.h\"")
print("")
print("const int16_t pixel_map[LED_RASTER_NUM_OUTPUTS*CHAIN_LENGTH] = {")

left_eye = np.loadtxt("left_eye.csv")

full_map = np.ones((64, 80))*-1
full_map[0:48, 0:32] = left_eye*3

for i in range(64*80):
    offset = int(full_map.flat[i])
    if (i % 8) == 0:
        print("    ", end='')
    print(f"{offset:5d}, ", end='')
    if (i % 8) == 7:
        print("")

print("};")
